---

driver:
  name: dokken
  chef_version: 12.18.31
  use_sudo: true
  privileged: false
  volumes: '/var/lib/docker'
  driver_config:
    ssl_verify_mode: ":verify_none"
    forward: 80

transport:
  name: dokken

verifier:
  name: inspec
  format: junit
  output: test/inspec/results/%{platform}_%{suite}_inspec.xml
#  output: $CIRCLE_TEST_REPORTS/inspec/results/%{platform}_%{suite}_inspec.xml

provisioner:
  name: dokken
  data_bags_path: test/data_bags
  encrypted_data_bag_secret_key_path: test/data_bags/encrypted_data_bag_secret
  roles_path: test/roles
  environments_path: test/environments
  chef_log_level: info

platforms:
  - name: amazonlinux
    driver_config:
      image: amazonlinux:latest
      intermediate_instructions:
        - RUN yum -y install upstart procps util-linux
      pid_one_command: /sbin/init

suites:
  - name: docker
    run_list:
      - role[bonusbits_mediawiki_nginx]
    provisioner:
      client_rb:
        environment: docker_environment
