---

driver:
  name: docker
  use_sudo: false # For Native Docker on Mac. Comment if using Toolbox (docker-machine)
  driver_config:
    ssl_verify_mode: ":verify_none"

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.18.31
  data_bags_path: test/data_bags
  encrypted_data_bag_secret_key_path: test/data_bags/encrypted_data_bag_secret
  roles_path: test/roles
  environments_path: test/environments

platforms:
  - name: amazonlinux
    driver_config:
      image: amazonlinux:latest
      platform: amazon

suites:
  - name: default
    run_list:
      - role[ec2_role]
    provisioner:
      client_rb:
        environment: ec2_environment
