---

driver:
  name: docker
  use_sudo: false # For Native Docker on Mac. Remove/Comment if using Toolbox (docker-machine)
  driver_config:
    ssl_verify_mode: ":verify_none"
    forward: 80

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.18.31
  data_bags_path: test/data_bags
  encrypted_data_bag_secret_key_path: test/data_bags/encrypted_data_bag_secret
  roles_path: test/roles
  environments_path: test/environments

platforms:
  - name: amazonlinux
    driver_config:
      image: amazonlinux:latest
      platform: rhel

verifier:
  name: inspec

suites:
  - name: docker
    run_list:
      - role[bonusbits_mediawiki_nginx]
    provisioner:
      client_rb:
        environment: example_docker_environment
