---

driver:
  name: ec2
  associate_public_ip: <%= ENV['AWS_PUBLIC_IP'] %>
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_ID'] %>
  security_group_ids:
  <% (1..5).collect { |n| ENV["AWS_SECURITY_GROUP_#{n}"] }.compact.each do |secgroup| %>
    - <%= secgroup %>
  <% end %>
  subnet_id: <%= ENV['AWS_SUBNET'] %>
  vpc_id: <%= ENV['AWS_VPC_ID'] %>
  iam_profile_name: <%= ENV['AWS_IAM_INSTANCE_PROFILE_1'] %>
  region: <%= ENV['AWS_REGION'] %>
  instance_type: t2.micro

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.18.31
  data_bags_path: test/data_bags
  encrypted_data_bag_secret_key_path: test/data_bags/encrypted_data_bag_secret
  roles_path: test/roles
  environments_path: test/environments

verifier:
  name: inspec

platforms:
  - name: amazonlinux-ec2
    driver:
      image_search:
        owner-id: 137112412989
        name: amzn-ami-hvm-2016.*x86_64-gp2
      tags:
        Name: kitchen-bonusbits-mediawiki-nginx-<%= ENV['USER'] %>
        Created-By: Test Kitchen
        Owner: <%= ENV['USER'] %>

transport:
  username: ec2-user
  ssh_key: <%= ENV['AWS_SSH_KEY_PATH'] %>

suites:
  - name: ec2
    run_list:
      - role[bonusbits_mediawiki_nginx]
    provisioner:
      client_rb:
        environment: ec2_environment